#> tsp:daydream/structures/check/spellaltar/spellaltar_west
#> generated by Ribosome
# Check for the spell crafting altar

# set success variable to 1
scoreboard players set @s tsp.success 1

# base/layer0
execute if score @s tsp.success matches 1 unless block ~-2 ~0 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~0 ~-1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~0 ~0 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~0 ~1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~0 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~0 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~0 ~-1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~0 ~0 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~0 ~1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~0 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~0 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~0 ~-1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~0 ~0 #tsp:daydream/spellaltar_top run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~0 ~1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~0 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~0 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~0 ~-1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~0 ~0 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~0 ~1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~0 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~0 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~0 ~-1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~0 ~0 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~0 ~1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~0 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0

# layer 1
execute if score @s tsp.success matches 1 unless block ~-1 ~1 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~1 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~1 ~-2 minecraft:light_blue_stained_glass run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~1 ~2 minecraft:light_blue_stained_glass run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~1 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~1 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0

# layer 2
execute if score @s tsp.success matches 1 unless block ~-1 ~2 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~2 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~2 ~-2 minecraft:light_blue_stained_glass run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~2 ~2 minecraft:light_blue_stained_glass run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~2 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~2 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0

# layer 3
execute if score @s tsp.success matches 1 unless block ~-1 ~3 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~3 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~3 ~-2 minecraft:light_blue_stained_glass run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~3 ~2 minecraft:light_blue_stained_glass run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~3 ~-2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~3 ~2 minecraft:stone_bricks run scoreboard players set @s tsp.success 0

# layer 4
execute if score @s tsp.success matches 1 unless block ~-1 ~4 ~-2 #tsp:daydream/spellaltar_top run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~4 ~2 #tsp:daydream/spellaltar_top run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~4 ~-1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~4 ~0 minecraft:stone run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~4 ~1 minecraft:stone_bricks run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~4 ~-2 #tsp:daydream/spellaltar_top run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~4 ~2 #tsp:daydream/spellaltar_top run scoreboard players set @s tsp.success 0

# check for air blocks
execute if score @s tsp.success matches 1 unless block ~-2 ~1 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~1 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~1 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~1 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~1 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~1 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~1 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~1 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~1 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~1 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~1 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~1 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~1 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~1 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~1 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~1 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~1 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~1 ~2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~2 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~2 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~2 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~2 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~2 ~2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~2 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~2 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~2 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~2 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~2 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~2 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~2 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~2 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~2 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~2 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~2 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~2 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~2 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~2 ~2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~3 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~3 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~3 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~3 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~3 ~2 minecraft:air run scoreboard players set @s tsp.success 0


execute if score @s tsp.success matches 1 unless block ~-1 ~3 ~-1 minecraft:stone_brick_stairs[facing=north, waterlogged=false, half=top, shape=straight] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~3 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~3 ~1 minecraft:stone_brick_stairs[waterlogged=false, half=top, facing=south, shape=straight] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~3 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~3 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~3 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~3 ~-1 minecraft:stone_brick_stairs[facing=north, waterlogged=false, half=top, shape=straight] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~3 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~3 ~1 minecraft:stone_brick_stairs[waterlogged=false, half=top, facing=south, shape=straight] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~3 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~3 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~3 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~3 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~3 ~2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~4 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~4 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~4 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~4 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-2 ~4 ~2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~4 ~-1 minecraft:stone_brick_stairs[shape=straight, half=bottom, waterlogged=false, facing=east] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~4 ~0 minecraft:stone_brick_stairs[shape=straight, half=bottom, waterlogged=false, facing=east] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~-1 ~4 ~1 minecraft:stone_brick_stairs[shape=straight, half=bottom, waterlogged=false, facing=east] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~4 ~-2 minecraft:stone_brick_stairs[shape=straight, facing=south, half=bottom, waterlogged=false] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~0 ~4 ~2 minecraft:stone_brick_stairs[facing=north, half=bottom, shape=straight, waterlogged=false] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~4 ~-1 minecraft:stone_brick_stairs[shape=straight, facing=west, half=bottom, waterlogged=false] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~4 ~0 minecraft:stone_brick_stairs[shape=straight, facing=west, half=bottom, waterlogged=false] run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~1 ~4 ~1 minecraft:stone_brick_stairs[shape=straight, facing=west, half=bottom, waterlogged=false] run scoreboard players set @s tsp.success 0

execute if score @s tsp.success matches 1 unless block ~2 ~4 ~-2 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~4 ~-1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~4 ~0 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~4 ~1 minecraft:air run scoreboard players set @s tsp.success 0
execute if score @s tsp.success matches 1 unless block ~2 ~4 ~2 minecraft:air run scoreboard players set @s tsp.success 0

execute if score @s tsp.success matches 1 unless block ~-2 ~1 ~2 minecraft:lectern[facing=west]{id: "minecraft:lectern"} run scoreboard players set @s tsp.success 0

# if successful
execute if score @s tsp.success matches 1 run function tsp:daydream/structures/create/spellaltar 
execute if score @s tsp.success matches 0 run kill @s 
